---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cdeprod/concourse
    tag: 'latest'

inputs:
- name: codeblue-cli
  path: codeblue

run:
  path: codeblue/ci/tasks/cli-unit.sh
