
# hello-go task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: autopcftest

outputs:
- name: coverage-results

run:
  path: sh
  args: 
    - autopcftest/ci/scripts/unit-test.sh