---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cdeprod/concourse
    tag: 'latest'

params:
  GCS_KEY:         replace-me

inputs:
- name: codeblue-cli
  path: codeblue
- name: version-semver
  path: version-semver

run:
  path: codeblue/ci/tasks/upload-cli.sh
